CREATE TABLE IF NOT EXISTS app_user (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_feature_permission (
    id BIGSERIAL PRIMARY KEY,
    admin_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    feature VARCHAR(40) NOT NULL,
    UNIQUE (admin_id, feature)
);

CREATE TABLE IF NOT EXISTS player (
    id BIGSERIAL PRIMARY KEY,
    display_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    skill_level VARCHAR(10) NOT NULL DEFAULT 'C',
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tournament (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    venue VARCHAR(255),
    start_time TIMESTAMP,
    court_count INTEGER NOT NULL DEFAULT 1,
    expected_players INTEGER NOT NULL DEFAULT 10,
    play_type VARCHAR(20) NOT NULL DEFAULT 'SINGLES',
    format VARCHAR(20) NOT NULL DEFAULT 'ROUND_ROBIN',
    touch_score INTEGER NOT NULL DEFAULT 11,
    max_score INTEGER NOT NULL DEFAULT 15,
    court_cost NUMERIC(14, 2) NOT NULL DEFAULT 0,
    food_cost NUMERIC(14, 2) NOT NULL DEFAULT 0,
    prize_cost NUMERIC(14, 2) NOT NULL DEFAULT 0,
    other_cost NUMERIC(14, 2) NOT NULL DEFAULT 0,
    prize_rate_1 NUMERIC(5, 2) NOT NULL DEFAULT 50,
    prize_rate_2 NUMERIC(5, 2) NOT NULL DEFAULT 30,
    prize_rate_3 NUMERIC(5, 2) NOT NULL DEFAULT 20,
    external_registration_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tournament_registration (
    id BIGSERIAL PRIMARY KEY,
    tournament_id BIGINT NOT NULL REFERENCES tournament(id) ON DELETE CASCADE,
    player_id BIGINT REFERENCES player(id) ON DELETE SET NULL,
    external_name VARCHAR(255),
    external_email VARCHAR(255),
    skill_level VARCHAR(10) NOT NULL DEFAULT 'C',
    source VARCHAR(20) NOT NULL DEFAULT 'INTERNAL',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    paid_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
    payment_status VARCHAR(40) NOT NULL DEFAULT 'UNPAID',
    withdrawn_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tournament_id, player_id),
    UNIQUE (tournament_id, external_email)
);

CREATE TABLE IF NOT EXISTS match_game (
    id BIGSERIAL PRIMARY KEY,
    tournament_id BIGINT NOT NULL REFERENCES tournament(id) ON DELETE CASCADE,
    team_a VARCHAR(255) NOT NULL,
    team_b VARCHAR(255) NOT NULL,
    score_a INTEGER NOT NULL DEFAULT 0,
    score_b INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'SCHEDULED',
    court_number INTEGER NOT NULL DEFAULT 1,
    round_number INTEGER NOT NULL DEFAULT 1,
    serving_team VARCHAR(1) NOT NULL DEFAULT 'A',
    score_order INTEGER NOT NULL DEFAULT 2,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS team_club (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS team_member (
    id BIGSERIAL PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES team_club(id) ON DELETE CASCADE,
    player_id BIGINT NOT NULL REFERENCES player(id) ON DELETE CASCADE,
    member_type VARCHAR(20) NOT NULL DEFAULT 'FIXED',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (team_id, player_id)
);

CREATE TABLE IF NOT EXISTS team_month_fund (
    id BIGSERIAL PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES team_club(id) ON DELETE CASCADE,
    fund_month DATE NOT NULL,
    monthly_fee NUMERIC(14, 2) NOT NULL DEFAULT 0,
    court_cost NUMERIC(14, 2) NOT NULL DEFAULT 0,
    previous_balance NUMERIC(14, 2) NOT NULL DEFAULT 0,
    notes TEXT,
    UNIQUE (team_id, fund_month)
);

CREATE TABLE IF NOT EXISTS team_member_payment (
    id BIGSERIAL PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES team_member(id) ON DELETE CASCADE,
    fund_month DATE NOT NULL,
    paid_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
    payment_status VARCHAR(40) NOT NULL DEFAULT 'UNPAID',
    notes TEXT,
    UNIQUE (member_id, fund_month)
);
